In [2]:
!mkdir -p drive
!google-drive-ocamlfuse drive

/bin/bash: google-drive-ocamlfuse: command not found

In [0]:
import sys
sys.path.insert(0, 'drive/')

In [4]:
!pip install -q keras
!pip install -q tensorflow
!pip install -q numpy
!pip install -q pandas
!pip install -q nltk
!pip install -U -q PyDrive
!pip install -U -q sumeval
!pip install -U -q ProgressBar
!pip install -U -q networkx
!pip install -U -q sumy

     |████████████████████████████████| 993kB 2.8MB/s
  Building wheel for PyDrive (setup.py) ... done
     |████████████████████████████████| 51kB 2.0MB/s
  Building wheel for sumeval (setup.py) ... done
  Building wheel for sacrebleu (setup.py) ... done
  Building wheel for ProgressBar (setup.py) ... done
     |████████████████████████████████| 92kB 3.5MB/s
     |████████████████████████████████| 10.5MB 8.5MB/s
  Building wheel for breadability (setup.py) ... done

In [0]:
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

# 1. Authenticate and create the PyDrive client.
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

# 2. Load a file by ID and create local file.
downloaded = drive.CreateFile({'id':'1RZ7L1ToT_f5cj73U26Dbi7sIm2V4xznF'}) # replace fileid with Id of file you want to access
downloaded.GetContentFile('wikihowAll.csv') # now you can use export.csv 

downloaded2 = drive.CreateFile({'id':'1_M0ya_yrrNwTEEPXjXycDM73KM8CR1Ln'}) # replace fileid with Id of file you want to access
downloaded2.GetContentFile('glove.6B.100d.txt') # now you can use export.csv

In [6]:
import pandas as pd
import numpy as np
import re
import nltk
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize 
from sklearn.utils.extmath import randomized_svd
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
import networkx
from sumy.parsers.plaintext import PlaintextParser
from sumy.nlp.tokenizers import Tokenizer
from sumy.summarizers.lex_rank import LexRankSummarizer
import heapq
from sumeval.metrics.rouge import RougeCalculator
from nltk.translate.bleu_score import sentence_bleu
from progressbar import ProgressBar

nltk.download('punkt')
nltk.download('wordnet')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [0]:
wikiHow = pd.read_csv("wikihowAll.csv")

In [8]:
wikiHow.shape

(215365, 3)

In [9]:
wikiHow.head()

                                            headline  ...                                               text
0  \nKeep related supplies in the same area.,\nMa...  ...   If you're a photographer, keep all the necess...
1  \nCreate a sketch in the NeoPopRealist manner ...  ...   See the image for how this drawing develops s...
2  \nGet a bachelor’s degree.,\nEnroll in a studi...  ...   It is possible to become a VFX artist without...
3  \nStart with some experience or interest in ar...  ...   The best art investors do their research on t...
4  \nKeep your reference materials, sketches, art...  ...   As you start planning for a project or work, ...

[5 rows x 3 columns]

In [10]:
wikiHow.isnull().sum()

headline     818
title          1
text        1071
dtype: int64

In [0]:
wikiHow = wikiHow.dropna()
wikiHow = wikiHow.drop(['title'], 1)
wikiHow['text']=wikiHow['text'].fillna("")
wikiHow['headline']=wikiHow['headline'].fillna("")
wikiHow = wikiHow.reset_index(drop=True)

In [12]:
wikiHow.head()

                                            headline                                               text
0  \nKeep related supplies in the same area.,\nMa...   If you're a photographer, keep all the necess...
1  \nCreate a sketch in the NeoPopRealist manner ...   See the image for how this drawing develops s...
2  \nGet a bachelor’s degree.,\nEnroll in a studi...   It is possible to become a VFX artist without...
3  \nStart with some experience or interest in ar...   The best art investors do their research on t...
4  \nKeep your reference materials, sketches, art...   As you start planning for a project or work, ...

In [13]:
wikiHow.tail()

                                                 headline                                               text
214289  \nConsider changing the spelling of your name....   If you have a name that you like, you might f...
214290  \nTry out your name.,\nDon’t legally change yo...   Your name might sound great to you when you s...
214291  \nUnderstand the process of relief printing.,\...   Relief printing is the oldest and most tradit...
214292  \nUnderstand the process of intaglio printing....   Intaglio is Italian for "incis­ing," and corr...
214293  \nUnderstand the different varieties of lithog...   Lithography is a big term often used to refer...

In [14]:
wikiHow.text[7440]

';\n,,, In and then out.\n\n,,,,'

In [15]:
wikiHow.headline[7440]

'\nPlace the ball where down to the ground and face the ball valve (the hard part of the ball) toward your position.,\nTake about 3 big step back to give you more room to work with, it also help when you strike the ball.\n\n,\nPlace yourself behind the ball, and pick the direction that you want the ball to go to.\n\n,\nTake a deep breath before taking the shot.,\nThen run up to the ball and place your supporting foot away from the ball about a couple inches.\n\n,\nUse all the power you had toward your kicking foot, and your upper body should leaning back a little bit to lift the ball up and over the wall.\n\n,\nKick the ball with your lace or your front foot because this give you more power and accurate toward your shot.\n\n,\nFinally hit the bottom of the ball fast and lower your body as you hit the ball.\n\n'

In [0]:
contractions = { 
"ain't": "am not",
"aren't": "are not",
"can't": "cannot",
"can't've": "cannot have",
"'cause": "because",
"could've": "could have",
"couldn't": "could not",
"couldn't've": "could not have",
"didn't": "did not",
"doesn't": "does not",
"don't": "do not",
"hadn't": "had not",
"hadn't've": "had not have",
"hasn't": "has not",
"haven't": "have not",
"he'd": "he would",
"he'd've": "he would have",
"he'll": "he will",
"he's": "he is",
"how'd": "how did",
"how'll": "how will",
"how's": "how is",
"i'd": "i would",
"i'll": "i will",
"i'm": "i am",
"i've": "i have",
"isn't": "is not",
"it'd": "it would",
"it'll": "it will",
"it's": "it is",
"let's": "let us",
"ma'am": "madam",
"mayn't": "may not",
"might've": "might have",
"mightn't": "might not",
"must've": "must have",
"mustn't": "must not",
"needn't": "need not",
"oughtn't": "ought not",
"shan't": "shall not",
"sha'n't": "shall not",
"she'd": "she would",
"she'll": "she will",
"she's": "she is",
"should've": "should have",
"shouldn't": "should not",
"that'd": "that would",
"that's": "that is",
"there'd": "there had",
"there's": "there is",
"they'd": "they would",
"they'll": "they will",
"they're": "they are",
"they've": "they have",
"wasn't": "was not",
"we'd": "we would",
"we'll": "we will",
"we're": "we are",
"we've": "we have",
"weren't": "were not",
"what'll": "what will",
"what're": "what are",
"what's": "what is",
"what've": "what have",
"where'd": "where did",
"where's": "where is",
"who'll": "who will",
"who's": "who is",
"won't": "will not",
"wouldn't": "would not",
"you'd": "you would",
"you'll": "you will",
"you're": "you are"
}

In [0]:
def clean_text(text,contradictions = True):
    # Convert words to lower case
    
    if type(text) is str:
        text = text.lower()
    
    # Replace contractions with their longer forms 
    if contradictions:
        text = text.split()
        new_text = []
        for word in text:
            if word in contractions:
                new_text.append(contractions[word])
            else:
                new_text.append(word)
        text = " ".join(new_text)
        
    if re.search(r'(\w+)', text) is None:
      #print(text)      
      text = ''
    if re.search(r'^(\w+)', text) is None:
      #print(text)      
      text = ''
      
      
    
    # Format words and remove unwanted characters
    text = re.sub(r'\<a href', ' ', text)
    text = re.sub(r'http\S+', '', text, flags=re.MULTILINE)
    text = re.sub(r'&amp;', '', text) 
    #text = re.sub(r'[_"\-;%()|+&=*%.,!?:#$@\[\]/]', ' ', text)
    text = re.sub(r'<br\s*\/?>', '', text)
    text = re.sub(r'<br />', ' ', text)
    text = re.sub(r'</a>', ' ', text)
    text = re.sub(r'=', ' ', text)
    text = re.sub(r'"', ' ', text)
    text = re.sub(r'  ', ' ', text)
    text = re.sub(r' ''',' ', text, flags=re.MULTILINE)
    #text = re.sub(r'[,.]+$', '', text)
    
    #text = re.sub(r'.+a n[^a-z]+''t.+','', text, flags=re.MULTILINE)
    text = re.sub(r'^([a-z]\s)+[a-z]$','', text, flags=re.MULTILINE)
    #text = re.sub(r'\'', ' ', text)

    return text

In [18]:
clean_summaries = []

for summary in wikiHow.headline:
    clean_summaries.append(clean_text(summary,contradictions = True))
print("Summaries are complete.")

Summaries are complete.

In [19]:
clean_texts = []
for text in wikiHow.text:
    clean_texts.append(clean_text(text,contradictions = True))
print("Texts are complete.")

Texts are complete.

In [20]:
clean_texts[15]

"whether you are teaching a skill, delivering information or increasing awareness, outline the goals of your workshop. what do you want your workshop participants to learn? this analysis may result in a list of specific skills you will be teaching, concrete topics you will cover, or simply a feeling you will inspire in your participants. think carefully about what you want to accomplish and why it is important.some examples of workshop objectives include: learn how to write a persuasive cover letter. learn how to break bad news to a patient. learn 5 techniques to get a reluctant student to talk in class. learn how to create an effective powerpoint presentation.; , will the workshop participants know one another or are they strangers? will they come in with knowledge about your topic or will they be completely unfamiliar with it? are they choosing to attend your workshop or is it a requirement for their job training? answers to all of these questions will affect how you organize your workshop.for example, if your audience already knows each other, you might be able to launch into group activities very quickly. if they are complete strangers, you might need to schedule extra time for icebreakers and introductions. , these are the times when participants are most awake and alert. you want your participants to be fully engaged and aware. if you can, avoid scheduling evening workshops after the workday when everyone is tired and impatient., pass around flyers, hang up posters, or contact suitable businesses to encourage workshop participation. having a catchy title helps, as does a brief explanation for why your workshop is important and necessary.be sure to include images as well as text in your flyers to catch people's attention. , a workshop is not the same as a large lecture. you want your group to be small enough to ask all their questions, practice their skills, and work together. but you also want your workshop to be large enough to keep things interesting. ideally a workshop will have 8-15 participants.sometimes you do not have a choice about your group size. if you have a very large group, find creative ways to make sure the size does not become overwhelming. for example, a group of 40 participants could be divided into 5 different break-out groups of 8 participants each. you could also bring in co-facilitators and co-presenters to handle groups that are larger than ideal. , some workshops require that participants do work well before the workshop takes place. perhaps they have to study journal articles, write a short story, or read one another's work. if your participants have homework to do before the workshop takes place, be sure that your expectations are clearly stated from the beginning. be sure to set hard deadlines if your students have to submit work to the group ahead of time. be clear about where and how your students should submit their work. will they have to give you hard copies, or will you circulate materials by email? , most workshops are time-limited. they can be as short as 30 minutes or as long as three days. but no matter what, you will only have a short period of time to impart your knowledge to participants.rather than covering absolutely everything in a short amount of time, think about the most important skills, techniques, and information you want your audience to gain. prioritize those in your lesson plan. , adults learn in all kinds of ways: visually, orally, through hands-on practice, or any combination of the above.remember that you might not know your participants' learning styles ahead of time, so you will want to have a variety of materials prepared. depending on the topic and objective of your workshop, you might want to prepare paper handouts, audio-visual aids, computer-based lesson plans, and role-playing activities., readings, case studies, lists of key terms, and quizzes are all possible teaching aids you might wish to prepare. it is best if you prepare these handouts well ahead of time. that way you can catch typos or errors. be sure to use a large, easy-to-read font. give each document a clear label and date so that your participants will be able to use these handouts in the future. if you have lengthy readings, consider precirculating these handouts to the group so that they can come in prepared.if you are handing out numerous documents, consider providing your participants with a folder or binder to keep their papers neat and organized. if you give this workshop often enough, you might even want to compile your materials into a bound book that you give to your attendees. , if you plan to present a slideshow, video clips, or sound clips, you will have to prepare these ahead of time. test them at home to make sure they are working correctly. make sure that they are in a format that can be used in your workshop space. it is wise to consult with your venue's a/v technicians to make sure that your materials can be presented properly. not all projectors are compatible with macintosh computers, for example. and some rooms might not have sound projection. make sure that your venue can accommodate whatever technology you wish to use. , if your workshop participants will be expected to complete a computerized quiz or participate in an online discussion forum, you will need to organize these materials ahead of time.think about whether your participants will have to bring in their own personal computers or devices, and notify them if so. if your participants will be expected to do activities online, be sure to consult with your venue's a/v technician. you will have to make sure that your workshop space is equipped with wireless internet, and you might have to ask for the network's password in advance. , depending on the topic and size of your workshop, you might want to bring in other team members to facilitate learning. an expert can provide a live demonstration of a new medical technique; a guest speaker might be able to tell a lively anecdote about why your workshop topic is important; and an assistant might be able to help you manage a large group. if you require help from anyone, make sure that you recruit them well ahead of time. the more prepared they are, the better your workshop will be. , interaction amongst a group of participants sets a workshop apart from other ways of learning. brainstorm educational group activities that are suitable to your workshop's objectives. keep in mind that activities can be done in pairs, small groups, or as a full group. make sure that you include enough opportunities for every workshop participant to contribute meaningfully to your workshop. some possible group activities include: debates. break the workshop into two groups and have each group argue for their position. think-pair-shares. ask your participants a discussion question. have them think about it on their own, discuss their thoughts with a partner, and then share their conclusions with the full group. question-and-answer sessions. if you have a lot of information to present, include your attendees in the discussion by allowing them to ask questions about the material. you can answer these questions yourself or ask other workshop participants to answer them. role-playing activities. assign participants roles to play in order to practice the new techniques they are learning. brainstorming sessions. ask your workshop to shout out as many ideas as they can think of. write them all down on a chalkboard or whiteboard. then ask your workshop to evaluate what they have come up with. , people are more focused on tasks when they have the chance to take short breaks.they are also more likely to remember what they have learned. schedule your workshop plan to include at least one 5-minute break per hour of your workshop. this will shorten your time with your participants but will make that time more valuable. , actual activities can often take 10-20% more time than we estimate.if you think a q-and-a session will last 10 minutes, it might very well last 12 minutes or longer. build in enough time for each major activity or topic you want to cover. resist the urge to cram in as much as possible: your participants will feel tired and rushed. if you are worried that your workshop will end early, you can always prepare a couple of optional extra activities that will reinforce learning. if you have time for them, great! and if not, no harm done. , workshops take a lot of work and energy. help keep your participants' energy levels up by providing healthy foods and beverages.ideally the costs of these snacks will be covered through participant registration fees or by the organization that asked you to lead the workshop. you should not have to pay for snacks out-of-pocket. try to avoid junk foods. unhealthy foods might give short bursts of energy but then will cause energy crashes very soon. that will leave your participants bored and tired. aim for energizing healthy snacks such as fruit, vegetables, hummus, and whole grain breads., leave yourself plenty of time to set up the space and get comfortable in the room. you might have to meet with a/v technicians, caterers, or your team members before your workshop begins as well. give yourself as much time as you can in case you have to troubleshoot or make last-minute adjustments to your workshop plan., computers, laptops, projectors, and speakers will all have to be fine-tuned in advance. after all, you want your workshop time to be productive: you do not want to spend it fiddling with technology. if you can, see if you can have the venue's a/v technician assist you with the set-up. you might not be familiar with the room's technological capabilities, and an expert might be able to set everything up more efficiently. , the way you arrange the chairs will depend on the size of your group, the size of the room, and the activities you have planned. ideally the group will be small enough to sit in a circle or semi-circle: this will help establish rapport and facilitate conversation.if everyone will need to look at the front to watch video clips or a live demo, perhaps a semi-circle or straight rows of seats is more appropriate., if you have notebooks or other workshop materials to hand out, place them on the tables or chairs in advance to save time during the workshop. make sure they are in the correct order and that they are clearly labeled. other materials you might need to set up in your workshop space include: snacks and beverages. name-tags and markers. pens and pencils. , arriving early allows you to set up, relax and get to know participants before the start of the workshop. this helps in building relationships with the participants. , once everyone is seated, you will have to orient them to your workshop. be sure to tell them your name and what they should call you. give a few words about why you should be considered an expert in the topic and what got you interested in it. explain to your participants what the goal of the workshop is and why it is important. it is also a good idea to give a rough outline of how the workshop will be run so that they can be prepared. try to limit this segment to just a couple of minutes. even if your topic is a serious one, consider using humor to lighten the mood and get everyone comfortable with one another. explain to your participants what the materials around the room are and what they should do with them. for example, you can ask people to fill out name-tags, grab a cup of coffee, and make sure they have their handouts. if you would rather that your participants not pull out their readings or laptops right away, you can tell them when those materials will be needed. , ask your participants to introduce themselves. limit the introductions to a few sentences by asking everyone to answer two or three specific questions, such as their names and what they hope to gain from the workshop. you do not want the icebreakers to go on forever, but it is important that your attendees feel comfortable talking in front of the group. you can also ask everybody to break the ice by answering a light-hearted question like what is your favorite movie? or what is your favorite bad song? , this is when all of your careful preparations can be put into action. have your outline in front of you, and try to stick to the outline if you can. feel free to tell your participants directly what you are doing and why. your lesson plan does not have to be a surprise, and your participants might appreciate being told why you've organized the workshop in the way that you did. for example, you might tell them: first we are going to go over our case studies to make sure we understand their nuances. after that, we will divide into small groups to determine an ideal solution to the problem.  we're going to spend some time learning key terms that will be useful to you as you learn this new computer program. after i explain these terms, we will take a quiz to make sure we are on the same page. after that, we will open things up for discussion.  please introduce yourself to the person sitting next to you. in a few minutes, you will role-play a counselor-student interaction with your partner. , it is good to have a plan for your workshop, but be prepared to alter your workshop's content based on the reactions and experiences of the participants. build some flex time into your lesson plan so that you can address their questions, concerns, and interests.you can even provide options for activities that your workshop group can vote on. this will allow you to focus on what really matters and skip over redundant or unnecessary content. , always follow up the delivery of information with the reinforcement of that information through some kind of group activity. interactive group work is a particularly effective method to teach problem-solving techniques. a workshop is not the same thing as a lecture, and you want to honor the thoughts and opinions of your workshop participants. let them teach each other at the same time that you are teaching them. for example, you can: deliver information in short spurts and then allow participants to ask questions. divide participants into groups to complete a task and ask them to report back to the entire group. show a video clip and then ask pairs of participants to discuss their reactions. provide advice about how to handle a difficult situation and then ask small groups of participants to role-play the scenario. have an expert demonstrate a technique and then ask your students to take a collaborative quiz about the technique. , you do not want to micromanage every stage of the workshop. your participants might get bored or annoyed.keep in mind that a workshop is different from a lecture or a typical meeting: it is a format that thrives on interaction, activity, and group work., scheduling breaks helps people assimilate the information and reflect. let participants know how often they will get breaks and the lengths of the breaks. this allows workshop attendees to plan accordingly for restroom usage, phone calls and other personal needs. do not skip breaks, even if you are running short on time. , attention spans begin to wane after 20 minutes of the same activity. view this fact as an opportunity for creativity instead of as a problem. change up your activities, ask your participants to rearrange their chairs, or schedule a break at least once every 20-30 minutes to keep everyone engaged and motivated., even if you are treating a serious topic, humor can be a great way to emphasize information and keep everyone attentive.think about ways that you can introduce humor in a responsible, ethical way into your presentations, discussions, and activities. this will also encourage your participants to remain relaxed, alert, and comfortable. , make sure that all of your workshop participants are treated equally and respectfully.this means that any leadership roles (such as group discussion leader) should be distributed evenly across the workshop. encourage quiet, shy participants to speak. you want everyone to feel heard and respected. similarly, you do not want a single participant's voice (or your own voice for that matter) to dominate the discussion. , most workshops will run smoothly. after all, the participants presumably want to be there and want to learn. however, there might be scenarios where somebody is unwilling to participate or might be insulting to a colleague. be professional no matter what, and encourage respectful behavior by modeling respectful behavior.be clear in what you expect from your participants. if you have a participant who is acting up or trying to bully a colleague, consider speaking privately with that person. emphasize the importance of what you are teaching, and tell them that you expect adult, professional behavior from them. , explain everything that your participants have learned over the course of the session.this will help emphasize how far they have come and what new skills they have acquired. refer explicitly to the objectives you laid out at the beginning of the workshop, and explain how you think the participants have met those objectives. congratulate your workshop for their hard work and for their new knowledge. , design an evaluation form that your participants can fill out in the last few minutes of the workshop. be sure that you leave them with enough time to comment and consider your questions carefully.immediate feedback not only will help you improve your workshop but will also help reinforce the learning your participants have undertaken.good questions to ask include: what is the stated objective of this workshop? did the workshop meet its stated objective? what activities helped your learning the most? the least? was the workshop an appropriate length? what workshop materials (handouts, readings, quizzes, etc.) were the most useful? which ones were the least useful? how have you learned or grown from this workshop? how do you think your colleagues have learned or grown? how would you change this workshop in the future? any suggestions for improvements? are there any topics that you would like to take a workshop on? , ask workshop attendees if you may contact them in the future for their input. some people need time to reflect back on their workshop experiences. following up with workshop participants several days or weeks later might reveal new insights. you can ask additional questions such as: how well have you retained the information you learned in the workshop? do you still find yourself thinking about the workshop? how has the workshop helped you at work? were there ways it could have helped you more? what materials have you found useful since the workshop? what materials have you thrown away or forgotten about? , if enough participants are interested in more advanced versions of your workshop, consider scheduling a part 2. in the follow-up workshop, you can address more of their questions, dig more deeply into the topic, or engage in more advanced versions of the techniques taught in part 1. be sure that your follow-up workshop is not too repetitive and that it is suitable for more advanced attendees."

In [21]:
clean_summaries[15]

'define the workshop objective., decide who your audience is., schedule your workshop for the morning or early afternoon., publicize your workshop., recruit 8-15 participants for your workshop., prepare your participants for the workshop., prioritize your goals for the workshop., prepare a variety of teaching aids., prepare paper handouts., arrange your audio-visual materials., organize your computer-based materials., recruit experts, speakers, and assistants., decide on your group activities., leave time for breaks., resist cramming., secure catering., arrive early., set up all equipment before participants arrive., arrange the chairs in advance., distribute materials., greet participants as they arrive., introduce yourself and the workshop., begin icebreakers., execute your lesson plan., be flexible., use interactive exercises to reinforce information., do not talk too much., stick to your scheduled breaks., switch up activities every 20-30 minutes., lighten the mood., maintain a respectful, democratic atmosphere., be prepared for the unexpected., conclude the workshop with a summary of what they have learned., get feedback immediately after the session., follow up with the participants a few days or weeks later., schedule a follow-up workshop if necessary.'

In [0]:
def tokenizer(text):
    document = text.strip()
    sentences = nltk.sent_tokenize(document)
    sentences = [sentence.strip() for sentence in sentences]
    #text = ' '.join(sentences)
    return sentences

In [23]:
sentences = tokenizer(clean_texts[713])
sentences

['you should not change yourself for a guy because then he will like the fake you and not the real you, and that is not good.',
 'that is taking the wrong direction.',
 'do not go there.',
 'do whatever you feel like doing and act however you feel like acting.',
 'dart if you feel like.',
 'if you usually pick your nose, pick your nose!',
 'wear what you like, say what you like, act how you like.',
 'do whatever you feel like.',
 'if you are genuinely a quiet, calm, serious sort of person be like that.',
 'if you are really kinda crazy, be crazy!',
 'if he does not like you for who you are, he is not worth it.',
 '; , he would rather see your face and real body then all that fake glob on your face and clothes that show your body off.',
 'its okay to put on some make-up, maybe even a little blush or something else (whatever you want) but - do not use what you feel is too much.',
 'it is for your own good.',
 'he will not see the real you if you put fake stuff on you when your really beautiful inside and out.',
 'do not care what other people think of you, say about you, or anyone who does not like you (in a mean way.)',
 'again, if he does not like you for who you are, he is not worth it.',
 ', a guy is not going to like you right away just because he sees you walking in the hall to class.',
 'try to get him to catch you glancing at him at least a few times .',
 'get him to stare at you through sheer willpower.',
 ', as said earlier, if you are not the bold, chatty type who finds it easy to talk to guys, do not do this, as you will not be being yourself if you talk to boys just to get another guy to be jealous when you would not normally.',
 'when around him (such as lunch, in the halls, or before and after school), let him start seeing you either talking to another guy, flirting with another guy, staring at another guy, or just with guy friends in general., before you do that, be sure he knows that you know he is around by force of will.',
 'do not glance at him as you do this.',
 'he may think you are trying to make him jealous and that is a turn-off.',
 ', for example, say you are in lunch, and he sees you with friends.',
 'do a dance move randomly if you are the kind of person that does this normally, or go to a guy and put your arm around him.',
 'do something like similar to this.',
 'other ways to make them want your attention include having something noticeably in common.',
 'notice what he is into and if you are into it too, advertise that!',
 'if you have a band tee-shirt he does, wear it.',
 "if you have a book you've noticed him reading, let him see you reading your copy, or something similar.",
 "wear his favourite sport's teams colours or some supporters gear, carry your binder decorated with greenpeace symbols if he has one, take your flute to school if he plays flute or join the chess club if he is in it.",
 'look for things you like that he likes and use them to make a connection.',
 'again, do not change yourself for him.',
 ', this will just mess you up, unless you are being true to yourself doing so.',
 "lots of people are conceited, do think they are all that and believe that they are incredibly popular, when they actually aren't.",
 'if that is you, do not change, be yourself.',
 ', be nice to him, if the opportunity arises even though you do not know home.',
 'be polite, hold the door for him, say hi, let him go in front of you in a queue, these acts are about all you can do with a boy you do not know and hardly see.',
 'also, smile.',
 'happy girls are the prettiest.',
 ', do not notice him and let him see you with other guys as much as possible.',
 'he will be eating out the palm of your hand in no time!']

In [0]:
def lemmatizer(sentences):
    lemmatizer = nltk.WordNetLemmatizer()
    for i in range(len(sentences)):
        #print(sentences[i])
        words = nltk.word_tokenize(sentences[i])
        words = [lemmatizer.lemmatize(word) for word in words]
        sentences[i] = ' '.join(words)
    return sentences

In [0]:
def stemmer(sentences):
    stemmer = PorterStemmer()
    for i in range(len(sentences)):
        #print(sentences[i])
        words = nltk.word_tokenize(sentences[i])
        words = [stemmer.stem(word) for word in words]
        sentences[i] = ' '.join(words)
    return sentences

In [0]:
def stopwords(sentences):
    stopword_list = nltk.corpus.stopwords.words('english')
    word_token_list = []
    filtered_sentence_item = [] 
    filtered_sentence = []
    
    for sentence in sentences:
        word_tokens = word_tokenize(sentence)
        word_token_list.append(word_tokens)
    
    for word_tokens in word_token_list:
        for word in word_tokens:
            if(word not in stopword_list):
                filtered_sentence_item.append(word)
                #print(filtered_sentence_item)
        filtered_sentence_item = ' '.join(filtered_sentence_item)
        filtered_sentence.append(filtered_sentence_item)
        #print(filtered_sentence_item)
        filtered_sentence_item = [] 
            
    return filtered_sentence

In [0]:
def vectorizer(Tdidf=True):
    if Tdidf:
        vectorizer = TfidfVectorizer(min_df=1,ngram_range=(1, 1))
    else:
        vectorizer = CountVectorizer(binary=False, min_df=1,ngram_range=(1, 1))
    return vectorizer

In [0]:
def td_matrix(sentences,vectorizer):
    feature_matrix = vectorizer.fit_transform(sentences)
    td_matrix = feature_matrix.transpose()
    #td_matrix = td_matrix.multiply(td_matrix > 0)
    return td_matrix

In [0]:
def svd(td_matrix):
    u, s, vt = randomized_svd(td_matrix,
                              n_components=1,
                              n_iter=100,
                              random_state=None)
    return u,s,vt

In [0]:
def CalculateRougeScores(refrence_summary,model_summary,scoring = False):
    rouge = RougeCalculator(stopwords=True, lang="en")
    rouge_1 = rouge.rouge_n(
            summary=model_summary,
            references=refrence_summary,
            n=1)
    rouge_2 = rouge.rouge_n(
            summary=model_summary,
            references=[refrence_summary],
            n=2)
    rouge_L = rouge.rouge_l(
            summary=model_summary,
            references=[refrence_summary])
    if (scoring == False):
        print("ROUGE-1: {}, ROUGE-2: {}, ROUGE-L: {}".format(
            rouge_1, rouge_2, rouge_L
        ).replace(", ", "\n"))
    
    return rouge_1,rouge_2,rouge_L

In [0]:
def CalculateBleuScores(refrence_summary,model_summary,scoring = False):
    refrence_summary_list = []
    rs =nltk.word_tokenize(refrence_summary)
    #print(r)
    refrence_summary_list.append(rs)
#     print(refrence_summary_list)
    model_summary = nltk.word_tokenize(model_summary)

#     print(model_summary)
#     a = [['good', 'quality', 'dog', 'food']]
#     b = ['a', 'good', 'dog', 'food']
    
    score = sentence_bleu(refrence_summary_list, model_summary,weights=(1, 0, 0, 0))
    if(scoring == False):
        print("BLEU Score: {} ".format(
            score,).replace(", ", "\n"))
    return score

In [0]:
def LsaSummarizer(text,summary,scoring = False):
    
    rouge_1 = 0
    rouge_2 = 0
    rouge_L = 0
    bleu = 0
    
    if  text and text.strip():
        sentences = tokenizer(text)
        original_sentences = sentences
        sentences = lemmatizer(sentences)
        #sentences = stemmer(sentences)
        sentences = stopwords(sentences)
        vectorizerVal = vectorizer(Tdidf=True)
        td_matrixVal = td_matrix(sentences,vectorizerVal)
        #print(td_matrixVal)
        u,s,vt = svd(td_matrixVal)
        #print(vt.shape)
        num_sentences = 1

        salience_scores = np.sqrt(np.dot(np.square(s), np.square(vt)))
        #print(len(salience_scores))
        top_sentence_indices = salience_scores.argsort()[-num_sentences:][::-1]
        top_sentence_indices.sort()
        #print(original_sentences)
        #print(top_sentence_indices)
        model_summary = ''
        if(scoring == False):
            print('Original Text: ' + text + '\n')
            print('Human Summary: ' + summary + '\n')      

            for index in top_sentence_indices:
                print ('Lsa Summarizer: ' + original_sentences[index] + '\n')
                model_summary = original_sentences[index]
        else:
             for index in top_sentence_indices:
                model_summary = original_sentences[index]

        rouge_1,rouge_2,rouge_L = CalculateRougeScores(summary,model_summary,scoring)
        bleu = CalculateBleuScores(summary,model_summary,scoring)
        #print(rouge_1,rouge_2,rouge_L,bleu)
        return rouge_1,rouge_2,rouge_L,bleu
    else:
        #print(rouge_1,rouge_2,rouge_L,bleu)
        return rouge_1,rouge_2,rouge_L,bleu

In [33]:
LsaSummarizer(clean_texts[7440],clean_summaries[7440])

(0, 0, 0, 0)

In [0]:
def similarity_matrix(vectorizer):
    feature_matrix = vectorizer.fit_transform(sentences)
    similarity_matrix = (feature_matrix * feature_matrix.T)
    return similarity_matrix

In [0]:
def similarity_graph(similarity_matrix):
    similarity_graph = networkx.from_scipy_sparse_matrix(similarity_matrix)
    scores = networkx.pagerank(similarity_graph)
    networkx.draw_networkx(similarity_graph)
    return scores

In [0]:
def TextRankSummarizer(text,summary,scoring = False):
    
    rouge_1 = 0
    rouge_2 = 0
    rouge_L = 0
    bleu = 0
    
    if  text and text.strip():
        sentences = tokenizer(text)
        original_sentences = sentences
        sentences = lemmatizer(sentences)
        sentences = stopwords(sentences)
        vectorizerVal = vectorizer(Tdidf=True)
        similarityMatrixVal = similarity_matrix(vectorizerVal)
        scores = similarity_graph(similarityMatrixVal)
#         print(scores)
        num_sentences = 1
        ranked_sentences = sorted(((score, index)
                               for index, score
                               in scores.items()),
                              reverse=True)

        top_sentence_indices = [ranked_sentences[index][1] for index in range(num_sentences)]
        top_sentence_indices.sort()
        model_summary = ''
        if(scoring == False):             
            print('Original Text: ' + text + '\n')
            print('Human Summary: ' + summary + '\n')
            for index in top_sentence_indices:
                if(len(original_sentences)> index):
                  print ('TextRank Summarizer: ' + original_sentences[index] + '\n')
                  model_summary = original_sentences[index]
        else:
                for index in top_sentence_indices:
                    if(len(original_sentences)> index):
                        model_summary = original_sentences[index]            

        rouge_1,rouge_2,rouge_L = CalculateRougeScores(summary,model_summary,scoring)
        bleu = CalculateBleuScores(summary,model_summary,scoring)
        return rouge_1,rouge_2,rouge_L,bleu
    else:
        return rouge_1,rouge_2,rouge_L,bleu

In [37]:
TextRankSummarizer(clean_texts[7440],clean_summaries[7440])

(0, 0, 0, 0)

In [0]:
def LexRankSummarizerSumy(text,humanSummary,scoring = False):
    
    rouge_1 = 0
    rouge_2 = 0
    rouge_L = 0
    bleu = 0
    
    if  text and text.strip():
        summarizer = LexRankSummarizer()
        parser = PlaintextParser.from_string(text,Tokenizer("english"))
        summary = summarizer(parser.document, 1)

        model_summary = ''
        if(scoring == False):
            print('Original Text: ' + text + '\n')
            print('Human Summary: ' + humanSummary + '\n')
            for sentence in summary:
                print('LexRank Summarizer: ' + str(sentence)+ '\n')
                model_summary = str(sentence)
        else:
            for sentence in summary:
                model_summary = str(sentence)            

        rouge_1,rouge_2,rouge_L = CalculateRougeScores(humanSummary,model_summary,scoring)
        bleu = CalculateBleuScores(humanSummary,model_summary,scoring)
        
        return rouge_1,rouge_2,rouge_L,bleu
    else:
        return rouge_1,rouge_2,rouge_L,bleu

In [39]:
LexRankSummarizerSumy(clean_texts[7440],clean_summaries[7440])

(0, 0, 0, 0)

In [0]:
def get_keywords(sentences):
    
    filtered_text = ' '.join(sentences)
    word_list = re.findall(r'\w+', filtered_text)    
    count_dict = {}
    
    for word in word_list:
        count_dict.setdefault(word, 0)
        count_dict[word] += 1

    keywords = set()
    
    for word , cnt in count_dict.items():
        word_percentage = count_dict[word] * 1.0 / len(word_list)
        if word_percentage <= 0.5 and word_percentage >= 0.001:
            keywords.add(word)
    
    return keywords

In [0]:
def calculate_sentence_weight(text,keywords):
    
    keywords = keywords
    sentence_weight = []
    sentence_weight_val = 0
    filtered_sentence_list = text.split('.')
    
    for sentence in filtered_sentence_list:
        sentence_list = sentence.split(' ')
        window_start = 0
        window_end = -1
        # calculating window start
        for i in range(len(sentence_list)):
            if sentence_list[i] in keywords:
                window_start = i
                break
        # calculating window end
        for i in range(len(sentence_list) - 1, 0, -1):
            if sentence_list[i] in keywords:
                window_end = i
                break

        window_size = window_end - window_start + 1
        # calculate number of keywords
        keywords_cnt = 0

        for word in sentence_list:
            if word in keywords:
                keywords_cnt += 1

        if window_start > window_end:
            sentence_weight_val = 0
        else:
            sentence_weight_val = keywords_cnt*keywords_cnt *1.0 / window_size
        
        sentence_weight.append((sentence_weight_val,sentence))
        sentence_weight.sort(reverse = True)
    
    return sentence_weight,sentence_list

In [0]:
def LuhnSummarizer(text,summary,scoring = False):

    rouge_1 = 0
    rouge_2 = 0
    rouge_L = 0
    bleu = 0
    
    if  text and text.strip():
        sentences = tokenizer(text)
        sentences = lemmatizer(sentences)
        sentences = stopwords(sentences)
        keywords = get_keywords(sentences)
        sentence_weight,sentence_list = calculate_sentence_weight(text,keywords)  

        #print sentence_weight
        ret_list = []
        ret_cnt = min(1 , len(sentence_list))

        for i in range (ret_cnt):
            ret_list.append(sentence_weight[i][1])

        model_summary = ''
        if(scoring == False):
            print('Original Text: ' + text + '\n')
            print('Human Summary: ' + summary + '\n')
            for sentence in ret_list:
                print ('Luhn Summarizer: ' + sentence + '\n')
                model_summary = sentence
        else:
            for sentence in ret_list:
                model_summary = sentence            

        rouge_1,rouge_2,rouge_L = CalculateRougeScores(summary,model_summary,scoring)
        bleu = CalculateBleuScores(summary,model_summary,scoring)
        return rouge_1,rouge_2,rouge_L,bleu
    else:
        return rouge_1,rouge_2,rouge_L,bleu

In [43]:
LuhnSummarizer(clean_texts[60],clean_summaries[60])

Original Text: before you approach your crush, you want to ease into the dance and get comfortable. talking with your friends is a great way to spend the first part of the dance. it also can show your crush if they are watching that you are a social and friendly person.; , even if you are nervous at the prospect of talking to your crush, try to have confident body language from the beginning of the dance to the end of the night. stand up straight, smile, and don’t try to hide yourself. people naturally attracted to confident and positive body language, and if your crush sees you looking uncomfortable or worried they might not want to dance.even if you feel nervous, smiling and standing up straight can actually trick your body into feeling calmer and more confident. that’s why even if you are nervous, you should fake it till you make it. try not to cross your arms or use other closed body language that hides your body. also try not to hang your head; instead keep it up with your chin level. also try not to fidget or anxiously tap your feet, as this will make you look nervous. , if you are comfortable dancing, dance with your friends at the beginning of the dance. this will show your crush that you like dancing, and may be open to the idea of dancing with them.try not to dance with another guy or girl. if it seems like you like someone else, your crush will be less likely to dance with you. , if you see your crush looking in your direction, look at them and smile. only do this if your crush is nearby or if they are looking at or near you. if you stare at them intensely, that might come across more creepy than cute.making this non-verbal contact is a good first step because it opens up the window for them to come over and say hello, or even ask you to dance!

Human Summary: hang out with your friends., have confident body language., dance with your friends., catch your crush’s eye.

Luhn Summarizer:  people naturally attracted to confident and positive body language, and if your crush sees you looking uncomfortable or worried they might not want to dance

ROUGE-1: 0.45454545454545453
ROUGE-2: 0.09999999999999999
ROUGE-L: 0.3636363636363636
BLEU Score: 0.23076923076923078

/usr/local/lib/python3.6/dist-packages/nltk/translate/bleu_score.py:490: UserWarning:
Corpus/Sentence contains 0 counts of 3-gram overlaps.
BLEU scores might be undesirable; use SmoothingFunction().
  warnings.warn(_msg)

(0.45454545454545453,
 0.09999999999999999,
 0.3636363636363636,
 0.23076923076923078)

In [0]:
def CountBasedSummarizer(text,summary,scoring = False):
    
    rouge_1 = 0
    rouge_2 = 0
    rouge_L = 0
    bleu = 0
    
    if  text and text.strip():
        sentences = tokenizer(text)
        original_sentences = sentences
        sentences = lemmatizer(sentences)
        #print(sentences)
        sentences = stopwords(sentences)  

        # Textte geçen her kelimenin sayısını buluyoruz.
        word2count = {}
        for sentence in sentences:  
            sentence = re.sub(r'\W', ' ', sentence)
            sentence = re.sub(r'\s+', ' ', sentence)
            for word in nltk.word_tokenize(sentence):
                    if word not in word2count.keys():
                        word2count[word] = 1
                    else:
                        word2count[word] += 1

        # Selecting best 50 features
        freq_words = heapq.nlargest(50, word2count, key=word2count.get)   
        # Textte en fazla geçen kelimenin sayısını diğer kelimelerin geçme sayılarına bölerek ağırlıkları buluyoruz.
        max_count = max(word2count.values())

        for key in word2count.keys():
            word2count[key] = word2count[key] / max_count
        # textteki cümleler içerisinde 25 kelimeden az olan sentence score  dictionarysini dolduruyoruz.

        sent2score = {}

        for sentence in original_sentences:  
            for word in nltk.word_tokenize(sentence.lower()):              
                if word in word2count.keys():
                    if len(sentence.split(' ')) < 50:
                        if sentence not in sent2score.keys():
                            sent2score[sentence] = word2count[word]
                        else:
                            sent2score[sentence] += word2count[word]
        #print(sent2score)
    #     return
        # heapq.nlargest dictionary deki scoreu en yüksek cümleyi getirir.
        best_sentences = heapq.nlargest(1, sent2score, key=sent2score.get)
        #print(best_sentences)
        model_summary = ''
        if(scoring == False):
            print('Original Text: ' + text + '\n')
            print('Human Summary: ' + summary + '\n')
            for sentence in best_sentences:
                print ('Count Based Summarizer: ' + sentence + '\n')
                model_summary = sentence
        else:
            for sentence in best_sentences:
                model_summary = sentence
        rouge_1,rouge_2,rouge_L = CalculateRougeScores(summary,model_summary,scoring)
        bleu = CalculateBleuScores(summary,model_summary,scoring) 
        
        return rouge_1,rouge_2,rouge_L,bleu
    else:
        return rouge_1,rouge_2,rouge_L,bleu

In [0]:
def Scoring():    
    pbar = ProgressBar()
    rouge_1_lsa = 0
    rouge_2_lsa = 0
    rouge_L_lsa = 0
    bleu_lsa = 0
    
    rouge_1_textrank = 0
    rouge_2_textrank = 0
    rouge_L_textrank = 0
    bleu_textrank = 0
    
    rouge_1_lexrank = 0
    rouge_2_lexrank = 0
    rouge_L_lexrank = 0
    bleu_lexrank = 0
    
    rouge_1_luhn = 0
    rouge_2_luhn = 0
    rouge_L_luhn = 0
    bleu_luhn = 0
    
    rouge_1_countbased = 0
    rouge_2_countbased = 0
    rouge_L_countbased = 0
    bleu_countbased = 0
    
    for i in pbar(range(len(clean_texts))):
        print(i)
        rouge_1,rouge_2,rouge_L,bleu = LsaSummarizer(clean_texts[i],clean_summaries[i],True)
        rouge_1_lsa = rouge_1_lsa + rouge_1
        rouge_2_lsa = rouge_2_lsa + rouge_2
        rouge_L_lsa = rouge_L_lsa + rouge_L
        bleu_lsa = bleu_lsa + bleu
        
        rouge_1,rouge_2,rouge_L,bleu = TextRankSummarizer(clean_texts[i],clean_summaries[i],True)
        rouge_1_textrank = rouge_1_textrank + rouge_1
        rouge_2_textrank = rouge_2_textrank + rouge_2
        rouge_L_textrank = rouge_L_textrank + rouge_L
        bleu_textrank = bleu_textrank + bleu

        rouge_1,rouge_2,rouge_L,bleu = LexRankSummarizerSumy(clean_texts[i],clean_summaries[i],True)
        rouge_1_lexrank = rouge_1_lexrank + rouge_1
        rouge_2_lexrank = rouge_2_lexrank + rouge_2
        rouge_L_lexrank = rouge_L_lexrank + rouge_L
        bleu_lexrank = bleu_lexrank + bleu
        
        rouge_1,rouge_2,rouge_L,bleu = LuhnSummarizer(clean_texts[i],clean_summaries[i],True)
        rouge_1_luhn = rouge_1_luhn + rouge_1
        rouge_2_luhn = rouge_2_luhn + rouge_2
        rouge_L_luhn = rouge_L_luhn + rouge_L
        bleu_luhn = bleu_luhn + bleu
        
        rouge_1,rouge_2,rouge_L,bleu = CountBasedSummarizer(clean_texts[i],clean_summaries[i],True)
        rouge_1_countbased = rouge_1_countbased + rouge_1
        rouge_2_countbased = rouge_2_countbased + rouge_2
        rouge_L_countbased = rouge_L_countbased + rouge_L
        bleu_countbased = bleu_countbased + bleu
        
    
    rouge_1_lsa_avg_score = rouge_1_lsa / len(clean_texts)
    rouge_2_lsa_avg_score = rouge_2_lsa / len(clean_texts)
    rouge_L_lsa_avg_score = rouge_L_lsa / len(clean_texts)
    bleu_lsa_avg_score = bleu_lsa / len(clean_texts)
    
    rouge_1_textrank_avg_score = rouge_1_textrank / len(clean_texts)
    rouge_2_textrank_avg_score = rouge_2_textrank / len(clean_texts)
    rouge_L_textrank_avg_score = rouge_L_textrank / len(clean_texts)
    bleu_textrank_avg_score = bleu_textrank / len(clean_texts)
    
    rouge_1_lexrank_avg_score = rouge_1_lexrank / len(clean_texts)
    rouge_2_lexrank_avg_score = rouge_2_lexrank / len(clean_texts)
    rouge_L_lexrank_avg_score = rouge_L_lexrank / len(clean_texts)
    bleu_lexrank_avg_score = bleu_lexrank / len(clean_texts)

    rouge_1_luhn_avg_score = rouge_1_luhn / len(clean_texts)
    rouge_2_luhn_avg_score = rouge_2_luhn / len(clean_texts)
    rouge_L_luhn_avg_score = rouge_L_luhn / len(clean_texts)
    bleu_luhn_avg_score = bleu_luhn / len(clean_texts)
    
    rouge_1_countbased_avg_score = rouge_1_countbased / len(clean_texts)
    rouge_2_countbased_avg_score = rouge_2_countbased / len(clean_texts)
    rouge_L_countbased_avg_score = rouge_L_countbased / len(clean_texts)
    bleu_countbased_avg_score = bleu_countbased / len(clean_texts)
    
    print("ROUGE-1-LSA: {}, ROUGE-2-LSA: {}, ROUGE-L-LSA: {}, BLEU-LSA: {}".
          format(rouge_1_lsa_avg_score,rouge_2_lsa_avg_score,rouge_L_lsa_avg_score,bleu_lsa_avg_score).replace(", ", "\n"))
    
    print("ROUGE-1-TextRank: {}, ROUGE-2-TextRank: {}, ROUGE-L-TextRank: {}, BLEU-TextRank: {}".
          format(rouge_1_textrank_avg_score,rouge_2_textrank_avg_score,rouge_L_textrank_avg_score,bleu_textrank_avg_score).replace(", ", "\n"))
    
    print("ROUGE-1-LexRank: {}, ROUGE-2-LexRank: {}, ROUGE-L-LexRank: {}, BLEU-LexRank: {}".
          format(rouge_1_lexrank_avg_score,rouge_2_lexrank_avg_score,rouge_L_lexrank_avg_score,bleu_lexrank_avg_score).replace(", ", "\n"))

    print("ROUGE-1-Luhn: {}, ROUGE-2-Luhn: {}, ROUGE-L-Luhn: {}, BLEU-Luhn: {}".
          format(rouge_1_luhn_avg_score,rouge_2_luhn_avg_score,rouge_L_luhn_avg_score,bleu_luhn_avg_score).replace(", ", "\n"))

    print("ROUGE-1-CountBased: {}, ROUGE-2-CountBased: {}, ROUGE-L-CountBased: {}, BLEU-CountBased: {}".
          format(rouge_1_countbased_avg_score,rouge_2_countbased_avg_score,rouge_L_countbased_avg_score,bleu_countbased_avg_score).replace(", ", "\n"))
    
    #print(rouge_1_lsa_avg_score,rouge_2_lsa_avg_score,rouge_L_lsa_avg_score,bleu_lsa_avg_score) 
    #return rouge_1_lsa_avg_score,rouge_2_lsa_avg_score,rouge_L_lsa_avg_score,bleu_lsa_avg_score

In [0]:
Scoring()

In [109]:
CountBasedSummarizer(clean_texts[486],clean_summaries[486])

ValueError: ignored

In [108]:
LsaSummarizer(clean_texts[486],clean_summaries[486])

ValueError: ignored

In [0]:
TextRankSummarizer(clean_texts[75],clean_summaries[75])

In [0]:
LexRankSummarizerSumy(clean_texts[75],clean_summaries[75])

In [0]:
LuhnSummarizer(clean_texts[75],clean_summaries[75])